### PR TITLE
Agenda

### LINKED ISSUE #5: Define Webinar Agenda
Define an agenda for the Webinar series.

### PR DESCRIPTION
**Pull request by KietNhiTran**
resolve #5

- Added agreed agenda

### CODE REVIEW

**Review by sajeetharan — COMMENTED** [review]
Looks good to me! may be we can merge once we are finalized on the dates

**Comment by GuideVMSFT** [comment]
LGTM 👍

**Review by GuideVMSFT — COMMENTED** [review]
LGTM 👍

**Review by PlagueHO — APPROVED** [review]
:lgtm:

**Comment by PlagueHO** [comment]
Just need @vitoc to approve and we can merge 😀 Thank you @KietNhiTran!

**Comment by KietNhiTran** [comment]
We need to review this one since it just was created based on the meeting minute last time. Giving the timeline is next week, I am not sure if the timing is working. :-)

**Pull request merged**
